name: halalin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  bottom_navy_bar: ^6.0.0
  camera: ^0.10.0+4
  convex_bottom_bar: ^3.1.0+1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_tesseract_ocr: ^0.4.20
  get: 4.6.5
  google_mlkit_commons: ^0.2.0
  google_mlkit_text_recognition:
    git:
      url: https://github.com/Thoriq-ha/google_mlkit_text_recognition.git
      ref: main
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  sliding_up_panel: ^2.0.0+1
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/ornamentTop.png
    - assets/images/ornamentBot.png
    - assets/images/ornamentAppbarLeft.png
    - assets/images/ornamentAppbarRight.png
    - assets/images/headline.png
    - assets/
    - assets/dataset/
    - assets/tessdata/
